### ISSUE TITLE
unexpected event error when calling `getAccount` from `@solana/spl-token`

### ISSUE THREAD

**Issue by mcintyre94** [coral-xyz/backpack#3363]
I've forked `xnft-quickstart` and added a minimal call to `getAccount` from `@solana/spl-token`. Code: https://github.com/mcintyre94/xnft-quickstart/blob/spl-token-test/src/screens/HomeScreen.tsx (spl-token-test branch of my fork)

I've added this code:

```
  const connection = useSolanaConnection();

  async function getTokenBalance(connection: Connection) {
    // Circle USDC account: https://explorer.solana.com/address/3emsAVdmGKERbHjmGfQ6oZ1e35dkf5iYcS6U4CPKFVaa
    const tokenAccountAddress = new PublicKey("3emsAVdmGKERbHjmGfQ6oZ1e35dkf5iYcS6U4CPKFVaa")
    const tokenAccount = await getAccount(connection, tokenAccountAddress)
    console.log({ balance: tokenAccount.amount })
  }

  useEffect(() => {
    if (!connection) return
    getTokenBalance(connection)
  }, [connection]);
```

I have backpack on mainnet and `connection.rpcEndpoint` shows as https://swr.xnfts.dev/rpc-proxy/

When I load this in backpack it displays an error:

```
Compiled with problems:
×
ERROR
unexpected event
    at RequestManager._handleRpcResponse (chrome-extension://bebbepljbdmldokgjifckgdmghloldoo/injected.js:2:2899717)
ERROR
unexpected event
    at RequestManager._handleRpcResponse (chrome-extension://bebbepljbdmldokgjifckgdmghloldoo/injected.js:2:2899717)
```

In the browser devtools console I see:

```
ERROR: backpack: common/request-manager: unexpected event MessageEvent injected.js:2 

Uncaught Error: unexpected event
    at RequestManager._handleRpcResponse (injected.js:2:2899717) injected.js:2 

ERROR: backpack: common/request-manager: unexpected event MessageEvent injected.js:2 

Uncaught Error: unexpected event
    at RequestManager._handleRpcResponse (injected.js:2:2899717)

bigint.ts:15 Uncaught (in promise) ReferenceError: Buffer is not defined
    at bigIntLayout.decode (bigint.ts:15:1)
    at Structure.decode (Layout.ts:1179:1)
    at unpackAccount (account.ts:174:1)
    at getAccount (account.ts:103:1)
```

If I expand the `MessageEvent` in that log I see what appears to be a reasonable response from a call to `getAccount`:

```
data: 
  detail: 
    id: 0
    result: 
      data: Uint8Array(165) [198, 250, 122, 243, 190, 219, 173, 58, 61, 101, 243, 106, 171, 201, 116, 49, 177, 187, 228, 194, 210, 246, 224, 228, 124, 166, 2, 3, 69, 47, 93, 97, 96, 101, 1, 179, 2, 225, 128, 24, 146, 248, 10, 41, 121, 245, 133, 248, 133, 93, 15, 32, 52, 121, 10, 36, 85, 247, 68, 250, 197, 3, 215, 181, 53, 57, 85, 131, 205, 92, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …]
      executable: false
      lamports: 2040720
      owner: j {_bn: i}
      rentEpoch: 361
 type: "channel-solana-connection-injected-response"
```
